name: Zephyr Release

on:
  push:
    branches:
      - main # Or your default branch

# !IMPORTANT: Prevents parallel runs and forces them into a safe queue.
concurrency:
  # The group name can be anything, but combining these two variables is best practice:
  # github.workflow: The name of this workflow (e.g., "Zephyr Release").
  # github.ref: The branch ref. Ensures pushes to different branches (e.g., 'main' vs 'dev') don't block each other.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  zephyr-release:
    runs-on: ubuntu-latest
    
    # Permissions are only needed if you use default GITHUB_TOKEN
    # For a PAT or GitHub App token, permissions are set by you on creation
    # permissions:
    #   contents: write       
    #   pull-requests: write 
    #   issues: write
    #   actions: write

    steps:
      # Optional checkout
      # - name: Checkout Code
      #   uses: actions/checkout@v4

      - name: Run Zephyr Release
        uses: Pandoriux/zephyr-release@v1
        with:
          token: ${{ secrets.CUSTOM_TOKEN }} # Omit this line to use the default GITHUB_TOKEN
          config-path: ".github/zephyr-release-config.jsonc"
          config-format: "jsonc"

          # Override specific config values directly in the workflow
          config-override: |
            {
              "name": "Override name"
            }
          
          # See docs for all available source-mode options: 
          # https://github.com/Pandoriux/zephyr-release/blob/main/docs/input-options.md#source-mode-optional
          source-mode: "local"