name: Zephyr Release

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  zephyr-release:
    runs-on: ubuntu-latest
    
    # Permissions are only needed if you use default GITHUB_TOKEN
    # For a PAT or GitHub App token, permissions are set by you on creation
    permissions:
      contents: write       
      pull-requests: write 
      actions: write

    steps:
      # Optional checkout
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Zephyr Release
        uses: owner/repo@v1
        with:
          token: ${{ secrets.CUSTOM_TOKEN }} # Omit this line to use the default GITHUB_TOKEN
          config-path: ".github/zephyr-release-config.jsonc"
          config-format: "jsonc"

          # Override specific config values directly in the workflow
          config-override: |
            {
              "name": "Override name"
            }
          
          # See docs for all available source-mode options: [link]
          source-mode: "local"