import * as v from "@valibot/valibot";
import { TimeZoneSchema } from "./components/timezone.ts";
import { CommitTypeSchema } from "./components/commit-type.ts";
import { VersionFileSchema } from "./components/version-file.ts";
import { CommandHookSchema } from "./components/command-hook.ts";
import { SEMVER_REGEX } from "../../../constants/semver.ts";
import { DEFAULT_COMMIT_TYPES } from "../../../constants/defaults/commit.ts";
import { transformObjKeyToKebabCase } from "../../../utils/transformers/object.ts";
import { trimNonEmptyStringSchema } from "../../string.ts";
import { RuntimeConfigOverrideSchema } from "./components/runtime-config-override.ts";
import { ExecutionModes } from "../../../constants/base-execution-modes.ts";

export const BaseConfigSchema = v.object({
  name: v.pipe(
    v.optional(v.pipe(v.string(), v.trim())),
    v.metadata({
      description: "Project name, available in string templates as {{ name }}.",
    }),
  ),
  timeZone: v.pipe(
    v.optional(TimeZoneSchema, "UTC"),
    v.metadata({
      description:
        "IANA timezone used to display times, available in string templates as {{ timeZone }}.\n" +
        'Default: "UTC"',
    }),
  ),
  mode: v.pipe(
    v.optional(v.enum(ExecutionModes), "proposal"),
    v.metadata({
      description:
        'Defines the execution strategy. "proposal" routes updates through a Pull Request. ' +
        '"auto" bypasses the PR and commits directly to the branch.\n' +
        'If choosing "auto", see release `autoStrategy`.\n' +
        'Default: "proposal"',
    }),
  ),

  commandHook: v.pipe(
    v.optional(CommandHookSchema),
    v.metadata({
      description:
        "Pre/post command lists to run around the main operation. Each command runs from the repository root.\n" +
        "Available variables that cmds can use: https://github.com/Pandoriux/zephyr-release/blob/main/docs/export-variables.md",
    }),
  ),
  runtimeConfigOverride: v.pipe(
    v.optional(RuntimeConfigOverrideSchema),
    v.metadata({
      description:
        "A dynamic configuration file to deep merge over the resolved config at runtime, typically " +
        "generated by a `commandHook` script.\n" +
        "This file is always read from the local filesystem. If the file does not exist or empty, it is safely ignored. " +
        "However, if the file exists but the merged result fails schema validation, the operation will throw an error.",
    }),
  ),

  customStringPatterns: v.pipe(
    v.optional(
      v.record(trimNonEmptyStringSchema, v.unknown()),
    ),
    v.metadata({
      description:
        "Custom string patterns to use in templates. The key is the pattern, available as '{{ <key> }}' while " +
        "the resolved value is the key value.",
    }),
  ),

  initialVersion: v.pipe(
    v.optional(v.pipe(v.string(), v.regex(SEMVER_REGEX)), "0.1.0"),
    v.metadata({
      description:
        "Initial SemVer version applied when no existing version is found.\n" +
        'Default: "0.1.0"',
    }),
  ),
  versionFiles: v.pipe(
    v.union([
      VersionFileSchema,
      v.pipe(v.array(VersionFileSchema), v.nonEmpty()),
    ]),
    v.transform((input) => Array.isArray(input) ? input : [input]),
    v.metadata({
      description:
        "Version file(s). Accepts a single file object or an array of file objects. If a single object, it becomes the " +
        "primary file. If arrays, the first file with `primary: true` becomes the primary; if none are marked, " +
        "the first file in the array will be used.\n" +
        "About primary file: https://github.com/Pandoriux/zephyr-release/blob/main/docs/config-options.md#version-files-required",
    }),
  ),

  localFilesToCommit: v.pipe(
    v.optional(
      v.union([
        trimNonEmptyStringSchema,
        v.pipe(
          v.array(trimNonEmptyStringSchema),
          v.nonEmpty(),
        ),
      ]),
    ),
    v.transform((input) => {
      if (input !== undefined) return Array.isArray(input) ? input : [input];
      return input;
    }),
    v.metadata({
      description:
        "Additional changed local files to include in the commit. Accepts a path or an array of paths/globs. " +
        'Paths are relative to the repo root. To include all files, use a glob such as "**/*".',
      examples: [["some/path"], ["src/release-artifacts/*"], ["**/*"]],
    }),
  ),

  commitTypes: v.pipe(
    v.optional(
      v.pipe(v.array(CommitTypeSchema), v.nonEmpty()),
      DEFAULT_COMMIT_TYPES,
    ),
    v.metadata({
      description:
        "List of commit types used for version calculation and changelog generation.\n" +
        `Default: ${
          JSON.stringify(
            transformObjKeyToKebabCase(DEFAULT_COMMIT_TYPES),
            null,
            2,
          )
        }`,
    }),
  ),
  stopResolvingCommitAt: v.pipe(
    v.optional(v.union([v.number(), trimNonEmptyStringSchema])),
    v.metadata({
      description:
        "Defines the boundary for resolving Git commit history. Can be a number or a string.\n" +
        "- Number: The maximum amount of commits to resolve (e.g., 50).\n" +
        "- String: The specific Git commit hash to stop at.",
    }),
  ),

  allowedReleaseAsCommitTypes: v.pipe(
    v.optional(
      v.union([
        trimNonEmptyStringSchema,
        v.pipe(v.array(trimNonEmptyStringSchema), v.nonEmpty()),
      ]),
      "<ALL>",
    ),
    v.transform((input) => Array.isArray(input) ? input : [input]),
    v.metadata({
      description:
        "List of commit type(s) allowed to trigger 'release-as'. Accepts single or array of strings.\n" +
        'Use "<ALL>" to accept any commit type; use "<COMMIT_TYPES>" to use the list defined in `commitTypes`. You can combine "<COMMIT_TYPES>" with other types (for example: ["<COMMIT_TYPES>","docs"]).\n' +
        "About 'release-as': https://github.com/Pandoriux/zephyr-release?tab=readme-ov-file#force-a-specific-version \n" +
        'Default: "<ALL>"',
      examples: ["<COMMIT_TYPES>", ["<COMMIT_TYPES>", "chore", "ci", "cd"]],
    }),
  ),
});

type _BaseConfigInput = v.InferInput<typeof BaseConfigSchema>;
type _BaseConfigOutput = v.InferOutput<typeof BaseConfigSchema>;
